### ISSUE TITLE
Failed to import - http2 (builtin node module)

### ISSUE THREAD

**Issue by hazae41** [ije/esm.sh#224]
## Failing module

- **GitHub**:  https://github.com/fauna/faunadb-js
- **npm**: faunadb / http2

```js
import { Client, Now } from "https://esm.sh/faunadb"
```

## Error message

After running `deno run` I get this:

```
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=http2&importer=faunadb
Download https://cdn.esm.sh/v51/deno_std_node_url.js
Check file:///C:/Users/hugog/Documents/stickorz/fauna/api/main.ts
error: Import 'https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=http2&importer=faunadb' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v51/faunadb@4.4.1/deno/faunadb.js:2:128
```

## Additional info

- **esm.sh version**: v55
- **Deno version**: 1.16.4

**Comment by talentlessguy** [comment]
there's no http2 module yet in deno_std

**Comment by Eusebiotrigo** [comment]
There is now an http2 module in https://deno.land/std@0.177.0/node/http2.ts

**Comment by ije** [comment]
already supported in fact，check https://github.com/ije/esm.sh/blob/4539a4c178c8d204f1e58109204ba5da5f3df8a8/server/nodejs.go#L131
