### ISSUE TITLE
Testing page with prod versions

### ISSUE THREAD

**Issue by johnpangalos** [ije/esm.sh#268]
Hey, esm.sh seems like a really cool project. Nice to have an alternative to skypack! I was looking at the website and noticed that when clicking on the testing page, the downloads seemed quite slow.

Looking at this for my use case (which is a static page website) gave me pause as it seemed to be quite slow until I realized that it was downloading the non minified versions of each package.

I was wondering if making a test page where you emphasize the speed of the client based downloads was interesting to the scope of this project. I would be will to help out if needed.

**Comment by ije** [comment]
it's slow because the `waterfell` since the testing page import a lot modules, you can change it to prod version, but i am not sure it can improve the speed very well

**Comment by johnpangalos** [comment]
The waterfall is not the issue I'm trying to point out, the issue is that if I were to be assessing whether or not to use esm.sh and find the testing page at the bottom I would potentially discount esm.sh because of the individual slow loading times presented in seconds on the testing page.

For example, if I were to see that using esm.sh with React on my page would add three seconds to my initial start time I wouldn't use it. I hope that's clearer.

**Comment by johnpangalos** [comment]
You could also add a note on the testing page saying that it's using development bundles and it does not reflect real world use. That would also mitigate this in my opinion.

**Comment by ije** [comment]
now it uses prod build, thanks
