### ISSUE TITLE
Does esm.sh work on China mainland?

### ISSUE THREAD

**Issue by fonsp** [ije/esm.sh#270]
Awesome work on esm.sh, thanks so much! I noticed that a CDN inside China was mentioned on the readme before, but it is now removed. Does esm.sh have good support inside China, [like jsdelivr.com](https://www.jsdelivr.com/network)?

**Comment by ije** [comment]
it works but vary slow, it's hard to say since China gov doesn't allow `.sh` domain even cloudflare can provide CDN in China.
