### ISSUE TITLE
Feature request: Support externals

### ISSUE THREAD

**Issue by Janpot** [ije/esm.sh#317]
Allow certain package imports to not be rewritten. e.g. when I import using `?externals=lodash` then the following imports remain untouched:

```js
import * as _ from 'lodash'
```

The reason is so that it could play well with import maps. e.g. when you have the following:

```html
<script type="importmap">
{
  "imports": {
    "lodash": "/node_modules/lodash-es/lodash.js"
  }
}
</script>
```

The browser knows how to resolve the bare `lodash` import, it doesn't need to be rewritten to an esm.sh url

**Comment by ije** [comment]
thanks, that makes sense for me, i will add it!

**Comment by jimisaacs** [comment]
This is a great idea, and my make aliasing without bundling moot.
Because an import map can alias for you.

**Comment by jimisaacs** [comment]
Come to think of it, would be cool to somehow let esm.sh know about an import map 🤔. It might be useful to have a blanket setting like "all dependencies are external".

**Comment by jimisaacs** [comment]
could it be `?externals` with empty value, means all dependencies are external, could result in static bundle name on cdn like `foopackagename.externals.js`
while `?externals=foodep,bardep` means only those dependencies are external, which would require a hashed bundle name on cdn.

**Comment by deckchairlabs** [comment]
Would love to see this! Will make things a whole lot nicer

**Comment by ije** [comment]
done! check https://esm.sh/preact-render-to-string@5.2.0?external=preact
