### ISSUE TITLE
Question How to bundle react-dom/client

### ISSUE THREAD

**Issue by colinfang** [ije/esm.sh#318]
I would like to download react esm and use it locally e.g.

```html
<script type="importmap">
{
    "imports": {
        "react": "/lib/react.js",
        "react-dom/client": "/lib/client.js"
    }
}
</script>
```

I downloaded the file referenced from <https://esm.sh/react> into `react.js`, and <https://esm.sh/react-dom?path=/client> into `client.js`

It seems to work with `react.js`. However in `client.js`, it referenced to the cdn version of `react-dom.js`  (The content is from <https://cdn.esm.sh/v78/react-dom@18.1.0/es2022/client.js>)

I tried bundled version. That seems to get rid of `react-dom`, but then it loads the cdn version of `react.js`  (The content is from <https://cdn.esm.sh/v78/react-dom@18.1.0/es2022/client.bundle.js>)

Is there a way to get react to work from local as es module without using build tools?

**Comment by ije** [comment]
i think this is related to #317, i am considering add the `external` feature

**Comment by ije** [comment]
try `?external`

**Comment by colinfang** [comment]
> try `?external`

It works gracefully
