### ISSUE TITLE
[feat] http only

### ISSUE THREAD

**Issue by loynoir** [ije/esm.sh#323]
### What
https://github.com/esm-dev/esm.sh/blob/46940b3b72de52cb2259d8973c9f959481e68dc4/server/embed/index.html#L41

Currently, a http only server is not working, unless `hostname` is hardcoded `localhost`.

### Feature Request
https://github.com/esm-dev/esm.sh/blob/46940b3b72de52cb2259d8973c9f959481e68dc4/server/embed/index.html#L26

Add a place holder to allow customize http only hostname

**Comment by jimisaacs** [comment]
are you saying something like `--http-only-hostname=localhost`

**Comment by loynoir** [comment]
> are you saying something like `--http-only-hostname=localhost`

Ah, yes 😃

**Comment by jimisaacs** [comment]
feels like a reasonable feature IMO, might take a crack at it myself

**Comment by loynoir** [comment]
@ije According to my local dirty patch, the backend part is not completed. Else got 302.

https://github.com/ije/esm.sh/blob/e2e2d2ee877b7c11561adb897cb196a466fd3346/server/utils.go#L280-L289

https://github.com/ije/esm.sh/blob/e2e2d2ee877b7c11561adb897cb196a466fd3346/server/query.go#L218

**Comment by ije** [comment]
pr welcome

**Comment by ije** [comment]
fixed in v89
