### ISSUE TITLE
Failed to import - twind/preset-tailwind-forms due to incorrect export transformation

### ISSUE THREAD

**Issue by KyleJune** [ije/esm.sh#325]
## Failing module

- **GitHub**: https://github.com/tw-in-js/twind/tree/next/packages/preset-tailwind-forms
- **npm**: https://www.npmjs.com/package/@twind/preset-tailwind-forms/v/next

```js
import * as twind from "https://esm.sh/twind@1.0.0-next.38?target=deno&pin=v78";
import presetTailwind from "https://esm.sh/@twind/preset-tailwind@1.0.0-next.38?target=deno&pin=v78";
import presetTailwindForms from "https://esm.sh/@twind/preset-tailwind-forms@1.0.0-next.38?target=deno&pin=v78";

const tw = twind.setup({
  presets: [
    presetTailwind(),
    presetTailwindForms(),
  ],
});

console.log(tw("bg-gray-800"));
```

The expected output is "bg-gray-800" but I'm getting an uncaught type error instead.

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: Cannot read properties of undefined (reading '500')
    at s (https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:1051)
    at preflight (https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:608)
    at Xt.Object.defineProperties.Object.getOwnPropertyDescriptors.target (https://cdn.esm.sh/v78/twind@1.0.0-next.38/deno/twind.js:2:11071)
    at file:///home/kyle/Projects/deno/udibo/example.js:12:13
```

## Additional info

- **esm.sh version**: 78
- **Deno version**: 1.21.1

Originally I created an issue on the twind repository [here](https://github.com/tw-in-js/twind/issues/317#issuecomment-1121422054) but the author was not able to reproduce the issue in their test suite and don't use deno.

I created a reproduction path to show it working using the node packages directly.

https://stackblitz.com/edit/tw-in-js-twind-qntfwj?file=package.json,index.js,index.html

If I try using the esm.sh imports instead with node as the target, it has the same issue as I do with the deno esm.sh imports.

https://stackblitz.com/edit/tw-in-js-twind-ph2pke?file=package.json,index.js,index.html

```
Uncaught TypeError: can't access property 500, o.gray is undefined
    s https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/node/preset-tailwind-forms.js:2
    preflight https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/node/preset-tailwind-forms.js:2
    Xt https://cdn.esm.sh/v78/twind@1.0.0-next.38/node/twind.js:2
    o https://cdn.esm.sh/v78/twind@1.0.0-next.38/node/twind.js:2
    i https://cdn.esm.sh/v78/twind@1.0.0-next.38/node/twind.js:2
    Zt https://cdn.esm.sh/v78/twind@1.0.0-next.38/node/twind.js:2
    ne https://cdn.esm.sh/v78/twind@1.0.0-next.38/node/twind.js:2
    <anonymous> https://tw-in-js-twind-ph2pke--3000.local-corp.webcontainer.io/index.js:10
preset-tailwind-forms.js:2:1008
```

I tried es2020 as the target too and it has the same error.

```
Uncaught TypeError: can't access property 500, o.gray is undefined
    s https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/es2020/preset-tailwind-forms.js:2
    preflight https://cdn.esm.sh/v78/@twind/preset-tailwind-forms@1.0.0-next.38/es2020/preset-tailwind-forms.js:2
    Xt https://cdn.esm.sh/v78/twind@1.0.0-next.38/es2020/twind.js:2
    o https://cdn.esm.sh/v78/twind@1.0.0-next.38/es2020/twind.js:2
    i https://cdn.esm.sh/v78/twind@1.0.0-next.38/es2020/twind.js:2
    Zt https://cdn.esm.sh/v78/twind@1.0.0-next.38/es2020/twind.js:2
    ne https://cdn.esm.sh/v78/twind@1.0.0-next.38/es2020/twind.js:2
    <anonymous> https://tw-in-js-twind-ph2pke--3000.local-corp.webcontainer.io/index.js?t=1652238125874:10
preset-tailwind-forms.js:2:1014
```

**Comment by KyleJune** [comment]
I found the issue by adding the &dev to the querystring. In the code sample below, `import * as colors from "...";` results in colors being the module instead of it being the default export.

```js
/* esm.sh - esbuild bundle(@twind/preset-tailwind-forms@1.0.0-next.38) deno development */
// esm-build-07a1b388834d79ce4071708cbd8b753e7575eddf-325f36f4/node_modules/@twind/preset-tailwind-forms/preset-tailwind-forms.js
import { toColorValue } from "/v78/twind@1.0.0-next.38/deno/twind.development.js";
import * as colors from "/v78/@twind/preset-tailwind@1.0.0-next.1/deno/colors.development.js";
import defaultTheme from "/v78/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.development.js";
// ...
"border-color": toColorValue(theme("colors.gray.500", colors.gray[500])),
```

If you look at that imported esm.sh file [here](https://esm.sh/v78/@twind/preset-tailwind@1.0.0-next.1/deno/colors.development.js), you'll see the following at the end of the file.

```js
export {
  colors_default as default
};
```

If you look at the actual file [here](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind/src/colors.ts) from the npm module, you will see that each key is actually exported as a const like shown below.

```js
export const gray = {
  50: '#f9fafb',
  100: '#f3f4f6',
  200: '#e5e7eb',
  300: '#d1d5db',
  400: '#9ca3af',
  500: '#6b7280',
  600: '#4b5563',
  700: '#374151',
  800: '#1f2937',
  900: '#111827',
} as const
```

The node module uses `import * as colors from "..."` and works correctly. You can see the full file [here](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind-forms/src/preset-tailwind-forms.ts#L16).

```
import { toColorValue } from 'twind'
import * as colors from '@twind/preset-tailwind/colors'
import defaultTheme from '@twind/preset-tailwind/defaultTheme'
```

So the issue is basically, in node, `colors.gray` is set correctly. In the esm.sh module, it has to be accessed via `colors.default.gray`. This causes preset-tailwind-forms to fail because it's trying to do `colors.gray` like it can for node.

**Comment by KyleJune** [comment]
As a temporary workaround, I've made a local copy of preset-tailwind-forms.js and changed `import * as colors from "...";` to `import { default as colors } from "...";` and the module works now.

After fixing that I also found an error in a types file. Below is the first line of the file followed by the error I get when I import the module in deno.

https://cdn.esm.sh/v78/@twind/preset-tailwind@1.0.0-next.38/preset-tailwind.d.ts
```ts
import { BaseTheme, MaybeArray, CSSProperties, Preset } from 'twind';
```

```
error: Relative import path "twind" not prefixed with / or ./ or ../
    at https://cdn.esm.sh/v78/@twind/preset-tailwind@1.0.0-next.38/preset-tailwind.d.ts:1:62
```

**Comment by KyleJune** [comment]
I think the issue is just that how colors.js is being transformed is not equivalent to the original. The [original](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind/src/colors.ts#L3) exports const while the only export in the esm transformed version is `export{f as default};` in https://esm.sh/v85/@twind/preset-tailwind@1.0.0-next.1/deno/colors.js.

This import signature works when each const is exported `import*as o from"/v85/@twind/preset-tailwind@1.0.0-next.1/deno/colors.js";` but does not work when the const keys are not exported. That's why my temporary patch of changing `* as o` to `{default as o}` works for resolving the issue. I think the ideal fix would be to change the exports for colors.js to match the original behavior.

**Comment by KyleJune** [comment]
After updating to v89 of esm.sh, I now get a different error.

```
error: TypeError: Cannot read properties of undefined (reading 'base')
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:2077
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:1309
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:7582
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.
```

It appears now the line for importing colors is getting transformed to `import ___twind_preset_tailwind_colors$$ from "/v89/@twind/preset-tailwind@1.0.0-next.38/deno/colors.js";`. I tried a similar workaround of changing it to `import * as ___twind_preset_tailwind_colors$$ from "/v89/@twind/preset-tailwind@1.0.0-next.38/deno/colors.js";`. but that didn't work.

The esm.sh page just says the following but it also appears to prevent esm.sh from minifying the code. 

> The ?dev mode builds modules with process.env.NODE_ENV equals to development, that is useful to build modules like React to allow you to get more development warn/error details.

I tried adding the dev flag to my twind imports and got the following error after doing so.

```
error: TypeError: Cannot read properties of undefined (reading 'base')
    var [baseFontSize, baseLineHeight] = defaultTheme__default.default.fontSize.base;
                                                                                ^
    at esm-build-1920456ca01153dd1b4c555a478d852f340170f1-ab7b87af/node_modules/@twind/preset-tailwind-forms/preset-tailwind-forms.cjs (file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.development.js:62:81)
    at __require2 (file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.development.js:19:50)
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v89/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.development.js:341:44
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.
```

Looking at that file, I found for each import it looks like esm.sh imports it twice, then combines the 2 into a single const with both the default and * imports.

```ts
import ___twind_preset_tailwind_defaultTheme$$ from "/v89/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.development.js";import * as ___twind_preset_tailwind_defaultTheme$$$ from "/v89/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.development.js";const ___twind_preset_tailwind_defaultTheme$ = Object.assign({ default: ___twind_preset_tailwind_defaultTheme$$ }, ___twind_preset_tailwind_defaultTheme$$$);
import ___twind_preset_tailwind_colors$$ from "/v89/@twind/preset-tailwind@1.0.0-next.38/deno/colors.development.js";import * as ___twind_preset_tailwind_colors$$$ from "/v89/@twind/preset-tailwind@1.0.0-next.38/deno/colors.development.js";const ___twind_preset_tailwind_colors$ = Object.assign({ default: ___twind_preset_tailwind_colors$$ }, ___twind_preset_tailwind_colors$$$);
```

Then here is where the combined import actually gets used. I added some logging at the end to see what the objects look like.

```ts
    var colors = ___twind_preset_tailwind_colors$;
    var defaultTheme = ___twind_preset_tailwind_defaultTheme$;
    var _interopDefault = (e) => e && e.__esModule ? e : { default: e };
    function _interopNamespace(e) {
      if (e && e.__esModule)
        return e;
      const n = /* @__PURE__ */ Object.create(null);
      if (e) {
        for (const k in e) {
          if (k !== "default") {
            const d = Object.getOwnPropertyDescriptor(e, k);
            Object.defineProperty(n, k, d.get ? d : {
              enumerable: true,
              get: () => e[k]
            });
          }
        }
      }
      n.default = e;
      return Object.freeze(n);
    }
    var colors__namespace = /* @__PURE__ */ _interopNamespace(colors);
    var defaultTheme__default = /* @__PURE__ */ _interopDefault(defaultTheme);
    console.log("colors", colors)
    console.log("colors__namespace", colors__namespace)
    console.log("defaultTheme", defaultTheme)
    console.log("defaultTheme__default", defaultTheme__default)
```

It appears that `defaultTheme` already had default on it because `defaultTheme__default` ends up being an object like `{default:{default:{...}}` after calling `_interopDefault(defaultTheme)`. Based on that I updated `_interopDefault` to also return `e` if `e.default` exists. That appears to have resolved the issue.

```ts
var _interopDefault = (e) => e && (e.__esModule || e.default) ? e : { default: e };
```

In the non dev version I replace `T=r=>r&&r.__esModule?r:{default:r}` with `T=r=>r&&r.__esModule||r.default?r:{default:r}` to get it to work without throwing an error.

It still has another issue that doesn't throw an error that I'm trying to track down. My twind styles no longer update when navigating between pages after this update. I may need to downgrade back to v85 to workaround that issue.

**Comment by KyleJune** [comment]
It appears the remaining issue I have is that either presetTailwindForms isn't being transformed correctly or the fix I came up with above breaks it. I checked my twind.ts file where it is used and found after updating from v85 to v89 of esm.sh, the twindConfig type is changing in a breaking way.

![image](https://user-images.githubusercontent.com/3241653/182052605-5ca86031-6be4-41cf-8abb-a13374df38d0.png)

Here is the type before when using v85 of esm.sh.

![image](https://user-images.githubusercontent.com/3241653/182052450-c58818b6-8a0f-4c00-b647-29522be9d42b.png)

Because of this issue and I don't know enough about esm.sh to fix this issue, I'm going to stick with esm.sh v85 for now with my earlier workaround for fixing the colors import.

**Comment by KyleJune** [comment]
I found another issue, it looks like if you pin a version of esm but also have deps set, those deps end up using the current version of esm.sh instead of the pinned version.

For example, this has v85 pinned but uses v89 for react and react-dom.

```
export {
  BrowserRouter,
} from "https://esm.sh/react-router-dom@6.3.0?target=deno&pin=v85&deps=react@18.2.0,react-dom@18.2.0";
```

**Comment by KyleJune** [comment]
I just checked the current version. This is still an issue. Here is the stacktrace for the error I get.

```
error: TypeError: Cannot read properties of undefined (reading 'base')
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v95/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:2098
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v95/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:1330
    at file:///home/kyle/Projects/deno/udibo/vendor/esm.sh/v95/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:7603
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.
```

**Comment by ije** [comment]
thanks！I will look into it！

**Comment by KyleJune** [comment]
It appears one of the versions between v95 and v99 fixed it. I didn't check each but know that it works now that I upgraded to v99.
