### ISSUE TITLE
Allow HEAD requests

### ISSUE THREAD

**Issue by Janpot** [ije/esm.sh#328]
If I only need access to the `X-TypeScript-Types` header, I can just do a HEAD request and avoid having to download the module content. Currently esm.sh responds with a `405` to such requests.

```
curl -IL -X HEAD https://esm.sh/lodash
HTTP/2 405 
date: Sun, 15 May 2022 20:04:25 GMT
content-type: application/json; charset=utf-8
content-length: 56
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Yk6eN5%2BpT1GWF7HkSNk7nFH2rVt%2FueIjdihzXo9C3PTznmDIfszOiXDslm%2Fgex5YteBPB5ZfeZnFU%2F4mRpD3%2BEcQRwI6X4nkxaP1ls0nOv8mHIomNTuDAa%2BYpAZr1bc8T35QTOs%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 70be7b88e88d83c6-BRU
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by jimisaacs** [comment]
This is in line with deno.land:
```
curl -IL -X HEAD https://deno.land/x/oak@v10.5.1/mod.ts
HTTP/2 405 
accept: GET
vary: Accept-Encoding
date: Mon, 16 May 2022 01:58:30 GMT
server: deploy/us-east4-c
```
I realize esm.sh has more use cases than a deno module registry, but curious what this would be used for?

**Comment by Janpot** [comment]
> curious what this would be used for?

One use-case I had was an online code editor that edited typescript files that import esm.sh urls. I only really needed the type definitions, if available.

**Comment by ije** [comment]
the `content-length: 56` is really small, and you always can get that size access package via `https://esm.sh/$PKG`
