### ISSUE TITLE
Failed to import - echarts，https://esm.sh/echarts No, but https://cdn.skypack.dev/echarts yes

### ISSUE THREAD

**Issue by gitfei1231** [ije/esm.sh#353]
<div id="chart-panel" style="width: 100vw; height: 100vh;"></div>

	<script type="module">
		// import * as echarts from "https://cdn.skypack.dev/echarts"; //正常显示
		import * as echarts from "https://esm.sh/echarts"; //不正常显示
		var chartDom = document.getElementById("chart-panel");
		var myChart = echarts.init(chartDom);
		var option;
		option = {
		  xAxis: {
		    type: "category",
		    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
		  },
		  yAxis: {
		    type: "value"
		  },
		  series: [
		    {
		      data: [150, 230, 224, 218, 135, 147, 260],
		      type: "line"
		    }
		  ]
		};
		option && myChart.setOption(option);
		//# sourceMappingURL=/index.js.map
	</script>

**Comment by gitfei1231** [comment]
@ije Can you help me look at this problem

**Comment by alienzhou** [comment]
I tried the code but it did not work after switching to `cdn.skypack.dev`. esm.sh and skypack both have some problems.

It seems that skypack does not replace the `process.env.NODE_ENV` variable. So it may throw an error
<img width="505" alt="image" src="https://user-images.githubusercontent.com/9822789/175886400-47db13ef-7b03-4fb9-a60b-23a5880bb113.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/9822789/175886489-4db25c9f-69c8-4fe1-880e-2b7d84e9bbf8.png">
> code from: https://cdn.skypack.dev/-/zrender@v5.3.2-Z3M16v6sUB3irOcbtWDn/dist=es2019,mode=imports/unoptimized/lib/zrender.js

---

The reason may be that the echart's modules import things from the zrender and its submodule. As a result, some 'internal states' won't be shared.

```javascript
// code from: https://esm.sh/v86/echarts@5.3.3/es2022/echarts.development.js

import * as zrender from "/v86/zrender@5.3.2/es2022/lib/zrender.development.js";
import { assert as assert13, each as each31, isFunction as isFunction12, isObject as isObject17, indexOf as indexOf6, bind as bind4, clone as clone8, setAsPrimitive as setAsPrimitive3, extend as extend13, createHashMap as createHashMap14, map as map15, defaults as defaults8, isDom, isArray as isArray20, noop as noop2, isString as isString18 } from "/v86/zrender@5.3.2/es2022/lib/core/util.development.js";
import env5 from "/v86/zrender@5.3.2/es2022/lib/core/env.development.js";
import timsort from "/v86/zrender@5.3.2/es2022/lib/core/timsort.development.js";
import Eventful2 from "/v86/zrender@5.3.2/es2022/lib/core/Eventful.development.js";
```

---

Currently using a bundled version may helps. You can add the 'bundle' query to the link:

```javascript
// import * as echarts from "https://esm.sh/echarts";
import * as echarts from "https://esm.sh/echarts?bundle"; // works
```

**Comment by gitfei1231** [comment]
@alienzhou thank you, cdn.skypack.dev I added code and it works，<script>window.process = { env: { NODE_ENV:  'production'} }</script>。

**Comment by gitfei1231** [comment]
@alienzhou The bundle file is relatively large. If you do not use the bundle, do you have to wait for the author to repair it

**Comment by alienzhou** [comment]
> @alienzhou The bundle file is relatively large.

The total files' size in esm.sh and skypack are almost the same. Although the no-bundled echarts package is small, it needs to import the zrender package.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/9822789/175923517-91823138-a891-40b9-82a6-68b229be41c2.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/9822789/175923618-cb9f95cf-17ca-4d63-8e21-e9218d79f873.png">

It could have cost. When you want to import the zrender package directly (or used by another package), it will have additional cost to fetch a seperated zrender module.

**Comment by gitfei1231** [comment]
> 现在 esm.sh 尝试捆绑子模块。也许改变这种行为会解决这个问题。我稍后会尝试。

Yes, thank you

**Comment by gitfei1231** [comment]
> 现在 esm.sh 尝试捆绑行为子模块。可能会改变这种情况。稍后我会尝试。

Thanks for using the latest code you submitted. Everything is normal at present
