### ISSUE TITLE
Uncaught SyntaxError: The requested module 'https://esm.sh/v86/keycode@2.2.1/es2022/keycode.js' does not provide an export named 'codes'

### ISSUE THREAD

**Issue by cristiano-belloni** [ije/esm.sh#362]
Hello,
I'm trying to run a third party application that imports `{ codes }` as a name dependency from `keycode`:

```js
import { codes } from 'keycode';
```

This works perfectly when bundled, but doesn't work with esm.sh:

```js
import { codes } from 'https://esm.sh/keycode@2.2.1'
```

-> Uncaught SyntaxError: The requested module 'https://esm.sh/v86/keycode@2.2.1/es2022/keycode.js' does not provide an export named 'codes'

It seems that `keycode.js` is missing all the named exports that should be extracted from the source cjs module and only has the default, combined one. Might this be because keycode does things like `var codes = exports.code = exports.codes = {...}` and trips the esm translation algorithm?

**Comment by roziscoding** [comment]
I have a similar error when importing [vscode-oniguruma](https://github.com/microsoft/vscode-oniguruma)
