### ISSUE TITLE
Add `conditions: "development"` for `?dev` imports

### ISSUE THREAD

**Issue by modderme123** [ije/esm.sh#375]
First of all, thanks for creating an awesome and fast tool! I'm looking at using it inside the SolidJS playground and it is super useful!

One issue I ran into was SolidJS uses different node conditions and already builds dev versions of the package, exported using the development condition for dev mode. It would be great if ?dev could automatically add that condition, but I thought I would check if that was wanted here before submitting a PR.

## Failing module

- **GitHub**: https://github.com/solidjs/solid
- **npm**: solid-js

```js
import { something } from 'https://esm.sh/solid-js?dev'
```

## Result

Searching the resulting bundle for `console.warn` doesn't yield anything (compare with https://cdn.jsdelivr.net/npm/solid-js@1.4.7/dist/dev.js)

## Additional info

- **esm.sh version**: v87

**Comment by ije** [comment]
close in https://github.com/ije/esm.sh/commit/049c2ba89ad59dfcdddbc5d31c9900b562a11dc0
