### ISSUE TITLE
[Feature Request] Support `deno` field for `package.json#exports`

### ISSUE THREAD

**Issue by brillout** [ije/esm.sh#376]
Since esm.sh is only used for Deno (correct me if I'm wrong) I believe esm.sh should support a `deno` field for `package.json#exports`.

For example:

```json5
{
  "name": "react-streaming",
  "exports": {
    "./server": {
      "node": "./dist/cjs/server.js",
      "deno": "./dist/esm/server.js"
    },
    "./client": {
      "browser": "./dist/esm/client.js"
    }
  }
}
```

Note the field `package.json#exports['./server'].deno`.

Also note that using `import` instead of `deno` is problematic because `dist/esm/server.js` doesn't work with Node.js.

**Comment by ije** [comment]
it supports, check https://github.com/ije/esm.sh/blob/266caad395b62b19646914f4c6613e96a790d511/server/nodejs.go#L436

**Comment by brillout** [comment]
Neat 👌.
