### ISSUE TITLE
Failed to import - isomorphic-ws

### ISSUE THREAD

**Issue by mnapoli** [ije/esm.sh#381]
## Failing module

- **GitHub**: https://github.com/heineiuo/isomorphic-ws
- **npm**: isomorphic-ws

It seems to be a dependency of a dependency:

```js
Download https://esm.sh/v89/isomorphic-ws@4.0.1/deno/isomorphic-ws.js
error: Import 'https://esm.sh/v89/isomorphic-ws@4.0.1/deno/isomorphic-ws.js' failed: 500 Internal Server Error
    at https://esm.sh/v89/@httptoolkit/websocket-stream@6.0.1/deno/websocket-stream.js:2:271
```

## Error message

After running `deno run` I got this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Can't resolve 'ws' in '/tmp/esm-build-3e27a3a2d1d1e90101eaea2756ad8d13ad0c3d6f-43763780/node_modules/isomorphic-ws'");
export default null;
```

See https://esm.sh/v89/isomorphic-ws@4.0.1/deno/isomorphic-ws.js

## Additional info

- **esm.sh version**: latest?
- **Deno version**: 1.23.1

**Comment by vyktoremario** [comment]
I also experienced this issue.
Is there a walk around?

**Comment by ije** [comment]
i will look into it asap！

**Comment by ije** [comment]
now it works check https://esm.sh/isomorphic-ws
