### ISSUE TITLE
error using path=/ in importmap

### ISSUE THREAD

**Issue by smcardle** [ije/esm.sh#386]
I have the following error in the console when trying to import webSocker from rxjs.
```
Failed to resolve module specifier "rxjs/webSocket". Import Map: "rxjs/webSocket" matches with "rxjs/" but is blocked due to backtracking
```

My rxjs importmap values are as follows -
```
          "rxjs": "https://esm.sh/rxjs@7.5.6?pin=v89",
          "rxjs/": "https://esm.sh/rxjs@7.5.6?pin=v89&path=/",
          "rxjs/operators": "https://esm.sh/rxjs@7.5.6/operators?external=rxjs&pin=v89",
```

And the code causing the error is as follows - 
```
      import {webSocket} from 'rxjs/webSocket'
      const subject$ = webSocket('wss://app.<domain>.com');
```
Does anybody know why I am getting the backtracking error ??

Steve

**Comment by ije** [comment]
try the esm.sh CLI mode i'm working on it: `deno run -A -r https://esm.sh add rxjs`

**Comment by smcardle** [comment]
I'm not using Deno.

The importmap is in the browser head section and has nothing to do with Deno

**Comment by ije** [comment]
or you can use `https://esm.sh/v89/rxjs@7.5.6/` instead of `https://esm.sh/rxjs@7.5.6?pin=v89&path=/`

**Comment by ije** [comment]
you can use `https://esm.sh/rxjs@7.5.6&pin=v89/` instead
