### ISSUE TITLE
__exportStar in tsc output not transpiled to esm 

### ISSUE THREAD

**Issue by nayeemrmn** [ije/esm.sh#389]
If a node typescript library has the following content:
```ts
export const foo = 1;
export * from './bar'
```
and the author transpiles it using `tsc` targeting cjs, they get something resembling:
```js
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "foo", { value: 1 });
__exportStar(require("./bar"), exports);
```
and they upload that to npm.

Understandably, esm.sh will recognise and generate an esm export for the `Object.defineProperty(exports, "foo", { value: 1 })` but not the `__exportStar((require("./bar"), exports)`. Despite the non-exactness I think it could be worth transpiling all instances of
```js
__exportStar(require("<specifier>"), exports);
```
to
```js
export * from "<specifier>";
```
As described above, this will enable a lot more modules from the Node/TS ecosystem to run correctly in browsers and Deno @ije.

<details>
<summary>Reproduction / example library (from @sinclairzx81)</summary>

- https://github.com/sinclairzx81/typebox/blob/0.24.27/src/value/index.ts
  - is transpiled with tsc targetting cjs / es2020 to
- https://pastebin.com/C3iqt2Ea
  - which is uploaded to npm and transformed by esm.sh to:
- https://esm.sh/v89/@sinclair/typebox@0.24.27/es2022/value/index.js
  - which doesn't contain the `export * from './value'` in the original source.

As a result, `import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value"` gives the following runtime error in Deno:
```
error: Uncaught SyntaxError: The requested module 'https://esm.sh/@sinclair/typebox@0.24.27/value' does not provide an export named 'Value'
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value";
         ^
```
</details>

**Comment by ije** [comment]
i  added `tslib.__exportStar` support in https://github.com/ije/esm.sh/blob/b81ea0f66c41a61f6db8666de3748ea0c629919f/packages/esm-cjs-lexer/src/test.rs#L597, but didn't consider the bundled `__exportStar`

**Comment by nayeemrmn** [comment]
@ije For some reason this fix can't be observed in https://esm.sh/v89/@sinclair/typebox@0.24.27/deno/compiler.js even though it can be observed in https://esm.sh/v89/@sinclair/typebox@0.24.27/es2022/compiler.js.

Whereas it works for both https://esm.sh/v89/@sinclair/typebox@0.24.27/es2022/value.js and https://esm.sh/v89/@sinclair/typebox@0.24.27/deno/value.js.

Any idea?
