### ISSUE TITLE
Failed to import react 18.2.0 types

### ISSUE THREAD

**Issue by oscarotero** [ije/esm.sh#402]
## Failing module

```js
import React from "https://esm.sh/react@18.2.0";
import ReactDOMServer from "https://esm.sh/react-dom@18.2.0/server";
```

## Error message

Related with https://github.com/lumeland/lume/issues/237

Looks like the types of React 18.2.0 don't exists, so Deno is continuously trying to download them

```
Download https://esm.sh/v90/@types/react-dom@~18.2/server~.d.ts
Download https://esm.sh/v90/@types/react@~18.2/index.d.ts
Download https://esm.sh/v90/@types/react-dom@~18.2/server~.d.ts
Download https://esm.sh/v90/@types/react@~18.2/index.d.ts
```

Maybe esm should detect the absence of types to don't include them if they don't exist. Or download the latest available version of types (react 18.0).

## Additional info

- **esm.sh version**: 90
- **Deno version**: 1.24.2

**Comment by ije** [comment]
this should be fixed in **v91** updates, can you please try again?

**Comment by oscarotero** [comment]
Seems to work fine. Thanks!
