### ISSUE TITLE
Failed to import - react-dom (from cdn.esm.sh due to http redirect)

### ISSUE THREAD

**Issue by PointDevs** [ije/esm.sh#405]
## Failing module

https://cdn.esm.sh/react-dom

This redirects to http://cdn.esm.sh/react-dom@18.2.0
which redirects to https://cdn.esm.sh/react-dom@18.2.0

The redirect to "http" causes the latest released versions of Chrome, Edge, and Firefox to fail to load the module

Console Errors: `Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS.`

Also, this affects the main page at https://cdn.esm.sh/ which suffers from the same failure to load modules.

**Comment by ije** [comment]
please remove the `cdn` subdomain, it's unnecessary now
