### ISSUE TITLE
https://esm.sh/ down, where to report timeouts?

### ISSUE THREAD

**Issue by dionjwa** [ije/esm.sh#406]
The service https://esm.sh/ seems to be down. 

The website is up, but attempting to import modules results in timeouts.

Module in question: https://esm.sh/@metapages/metapage@0.10.0

But I tried other modules. It seems that already-cached modules work, but not new modules.

Where to report issues such as this? Maybe a link on the main website?

**Comment by renhiyama** [comment]
@dionjwa I think this timeout occurs when esm.sh "builders" are failing to build this specific package 🤔 
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "Post \"http://localhost:8088\": dial tcp [::1]:8088: i/o timeout");
export default null;
```
This does mean esm.sh itself is fine, and I did confirm after publishing new versions of my npm packages, and esm.sh seems to load them just fine.

**Comment by kachkaev** [comment]
@ije 🙏

**Comment by ije** [comment]
i improved the node process handler, now it should work fine

**Comment by dionjwa** [comment]
Awesome thank you @ije !!!!  This service adds SO MUCH to the development story!
