### ISSUE TITLE
Whats up with url naming change from /v[0-9] to /stable ?

### ISSUE THREAD

**Issue by renhiyama** [ije/esm.sh#409]
My regex to find urls that import packages kinda went haywire when you guys changed urls from `/v91` to `/stable`

**Comment by cristiano-belloni** [comment]
It seems inconsistently applied too:

`https://esm.sh/react` -> `https://esm.sh/**stable**/react@18.2.0/es2022/react.js`
`https://esm.sh/lodash` -> `https://esm.sh/**v92**/lodash@4.17.21/es2022/lodash.js`

I'm experimenting with client side routing and this kills all my code :(

**Comment by ije** [comment]
the change is trying to fix #283

**Comment by renhiyama** [comment]
I'm now using `es-module-lexer` which seems good to replace with my regex. Closing this because my problem is now solved 👏
