### ISSUE TITLE
Failed to import - conf@10.2.0

### ISSUE THREAD

**Issue by char8x** [ije/esm.sh#410]
## Failing module

- **GitHub**: https://github.com/sindresorhus/conf
- **npm**: https://www.npmjs.com/package/conf

```js
import Conf from 'https://esm.sh/conf@10.2.0?dev';

const config = new Conf();

config.set('unicorn', '🦄');
console.log(config.get('unicorn'));
```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: onetime is not a function
        const getPackageData = onetime(() => {
                               ^
    at new Conf (https://esm.sh/v92/conf@10.2.0/deno/conf.development.js:134:32)
```

## Some discovery
<img width="860" alt="image" src="https://user-images.githubusercontent.com/6831013/186168306-b4d99c82-1f26-4a94-b4ba-07754e1bb2d5.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/6831013/186168701-8587cf06-8f81-46ea-8760-8fefc41949e8.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6831013/186168845-6c1756b8-0f40-4b34-8b34-e7cf84326ec1.png">

## Additional info

- **esm.sh version**: v92
- **Deno version**: 1.24.3

**Comment by kidonng** [comment]
I think this is the same issue as #411.
