### ISSUE TITLE
Serves v92 instead of v93

### ISSUE THREAD

**Issue by jaydenseric** [ije/esm.sh#415]
@ije esm.sh is still serving v92 if you import this:

```js
// @ts-check
import "https://esm.sh/react@18.2.0?dev";
import "https://esm.sh/react-dom@18.2.0/server?dev";
```

Cache is clean. There is something wrong with the CDN; it's not serving [v93](https://github.com/ije/esm.sh/releases/tag/v93) so https://github.com/ije/esm.sh/issues/331 in practice is not fixed.

<img width="892" alt="Screen Shot 2022-09-05 at 8 37 04 am" src="https://user-images.githubusercontent.com/1754873/188336071-3c3d01da-e16d-4ac8-9294-7f0c290a49f6.png">

**Comment by ije** [comment]
sorry, i forgot to purge the CDN cache, can you please try again?

<img width="632" alt="Screen Shot 2022-09-05 at 15 19 24" src="https://user-images.githubusercontent.com/2883484/188391080-ce7b97fd-b8b6-4cc7-858a-0794140d97dd.png">

**Comment by ije** [comment]
sorry, i forgot to purge the CDN cache, can you please try again?

<img width="632" alt="Screen Shot 2022-09-05 at 15 19 24" src="https://user-images.githubusercontent.com/2883484/188391080-ce7b97fd-b8b6-4cc7-858a-0794140d97dd.png">
