### ISSUE TITLE
Self-hosting: the CDN redirects to http instead of https

### ISSUE THREAD

**Issue by cristiano-belloni** [ije/esm.sh#421]
Hi, I'm self-hosting esm.sh. I'm on a platform that proxies connections, so the esm.sh instance runs on a normal http port (given by the platform on an environment variable, specified at start time using the `--port $PORT` option) and the platform proxies every connection to it serving via, and redirecting to, https. There is no option to use an https port.

I recently upgraded from v86 to > v89 (I tested 89 and 95), and I found that now the CDN responds to queries by exporting http v89 URLs. In other words, a query to **https**://my-hosted-cdn/react@18.2.0 returns the string 'export * from "**http**://my-hosted-cdn/v89/react@18.2.0/es2022/react.js"'. This obviously causes problems for the applications using esm.sh, that import from an https URL and get redirected to an http one.

This didn't happen in v86 - `https` URLs were generated as long as the Origin used `https`. I think the configuration where a service listens on a normal http port and is proxied to an https address is common enough to make it "just work" like it used to do before.

**Comment by ije** [comment]
you need to add `--origin https://you-cdn-name`, the server always get http request via proxy
