### ISSUE TITLE
Failed to import - ts-morph

### ISSUE THREAD

**Issue by paulshen** [ije/esm.sh#424]
## Failing module

- **npm**: https://www.npmjs.com/package/ts-morph

```js
import 'https://esm.sh/ts-morph'
```

## Error message

When importing `ts-morph`, I see a subsequent request to https://esm.sh/v95/@ts-morph/common@0.17.0/es2022/common.js return a 500. When I open in new tab, I see the following error.

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "npm: can't get metadata of package 'os-browserify/browser' (405 Method Not Allowed: {\"code\":\"MethodNotAllowedError\",\"message\":\"GET is not allowed\"})");
export default null;
```

This import used to work although I don't know what changed. https://esm.sh/ts-morph

## Additional info

- **esm.sh version**: 95
- **Browser version**:  Arc Version 0.69.0 (34772)
Chromium Engine Version 105.0.5195.127

**Comment by ije** [comment]
thanks! i will look into it
