### ISSUE TITLE
Failed to import - browserslist

### ISSUE THREAD

**Issue by saneef** [ije/esm.sh#429]
## Failing module

- **GitHub**: https://github.com/browserslist/browserslist
- **npm**: https://www.npmjs.com/package/browserslist

Accessing URL: https://esm.sh/browserslist@4.21.4 on WebKit browsers gives HTTP 500

## Error message

Response:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "yarn add browserslist@4.21.4: ");
export default null;
```

## Additional info

- **esm.sh version**: 96
- **Browser version**: 
    - Safari, 16.0
    - Safari Technology Preview, Release 155 (Safari 16.4, WebKit 17615.1.7.1)

**Comment by ije** [comment]
it's recovered now, the server was out of the disk space that is stolen by npm cache

**Comment by saneef** [comment]
Thank you!
