### ISSUE TITLE
Failed to import - trealla

### ISSUE THREAD

**Issue by guregu** [ije/esm.sh#431]
## Failing module

- **GitHub**: https://github.com/guregu/trealla-js
- **npm**: https://www.npmjs.com/package/trealla

```js
import { load, Prolog } from 'https://esm.sh/trealla@0.12.0';
```

## Error message

esm.sh returns a 500 error with this content:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "yarn add trealla@0.12.0: ");
export default null;
```

## Additional info

~~`trealla@v0.11.6` and lower seem to be OK. v0.11.7 and above are broken.
The changes from v0.11.6 to v0.11.7 don't seem to be significant: https://github.com/guregu/trealla-js/commit/5df8963c232a66fc798136159ab4e3582766f0f5~~

Edit: Nevermind about the version stuff, I think it's just a good build from an older esm.sh cached.

- **esm.sh version**: v96
- **Browser version**: Chrome Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by ije** [comment]
it's recovered now, the server was out of the disk space that is stolen by npm cache

**Comment by guregu** [comment]
Thanks a bunch! esm.sh is awesome ❤️
