### ISSUE TITLE
No X-Typescript-Types for:`@vanilla-extract/css`

### ISSUE THREAD

**Issue by xnuk** [ije/esm.sh#436]
## Failing module

- **GitHub**: https://github.com/vanilla-extract-css/vanilla-extract
- **npm**: https://www.npmjs.com/package/@vanilla-extract/css

`@vanilla-extract/css@1.9.1` in esm.sh does not gives `x-typescript-types` header:

```sh
$ curl --dump-header - 'https://esm.sh/@vanilla-extract/css@1.9.1' 2>/dev/null | grep x-typescript
$ # Nothing
```

But in https://registry.npmjs.org/@vanilla-extract/css/1.9.1 `package.json` contains `types` field:
```json
{ "types": "./dist/vanilla-extract-css.cjs.d.ts" }
```

Which is not suitable for Deno (because of extension) even if `?target=deno` is given:
```sh
$ curl --get 'https://esm.sh/@vanilla-extract/css@1.9.1/dist/vanilla-extract-css.cjs.d.ts?target=deno'
export * from "./declarations/src/index";
```

## Additional info

- **esm.sh version**: v96
- **Deno version**:
  - deno 1.26.2 (release, x86_64-unknown-linux-gnu)
  - v8 10.7.193.16
  - typescript 4.8.3

**Comment by ije** [comment]
Just checked, you can not find the `types` field in the package.json by downloading with npm/yarn which is how esm.sh server fetch package files

**Comment by xnuk** [comment]
Closing this for now since v106 shows the types properly.

**Comment by xnuk** [comment]
fyi: I've filed an issue for .d.ts inside of subpaths: https://github.com/vanilla-extract-css/vanilla-extract/issues/983
