### ISSUE TITLE
Failed to import - graphql in v96 (worked in v95)

### ISSUE THREAD

**Issue by dchambers** [ije/esm.sh#437]
Hi 👋. Thanks for this amazing service! I just wanted to report a regression I've started seeing in v96, but which worked prior.

## Failing module

- **GitHub**: https://github.com/graphql/graphql-js
- **npm**: https://www.npmjs.com/package/graphql

```ts
import { visit } from 'https://esm.sh/graphql@16.5.0?pin=v96'
```

## Error message

After running `deno run` I got this:

```
TS2305 [ERROR]: Module '"https://esm.sh/v96/graphql@16.5.0/graphql.d.ts"' has no exported member 'visit'.
```

## Additional info

- **esm.sh version**: `v96`
- **Deno version**: `1.23.4`

**Comment by ije** [comment]
thanks! i will look into it

**Comment by dchambers** [comment]
This is now working since today's `v97` release 🎉 . Thanks so much for fixing this 🙏.
