### ISSUE TITLE
Failed to import / failed to cache (deno)

### ISSUE THREAD

**Issue by spencercap** [ije/esm.sh#447]
## Failing module

hey, this looks like a great project, but I cannot seam to fetch our library algonautjs. 
i'm trying: https://esm.sh/@thencc/algonautjs@0.1.78 and i get:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "yarn add @thencc/algonautjs@0.1.78: error An unexpected error occurred: \"Failed to replace env in config: ${ESM_NPM_TOKEN}\".\n");
export default null;
```

- **GitHub**: https://github.com/thencc/algonautjs
- **npm**: https://www.npmjs.com/package/@thencc/algonautjs

```js
import { Algonaut } from 'https://esm.sh/@thencc/algonautjs@0.1.78';
// cannot even get this far are as the deno cannot cache the pkg
```

## Error message

I use the VSCode's quick tip for Deno to cache this library but get the error:
```
Import 'https://esm.sh/@thencc/algonautjs@0.1.78' failed: 500 Internal Server Error
```

## Additional info

- **esm.sh version**: 
- **Deno version**: deno 1.27.1 (release, x86_64-apple-darwin)
- v8 10.8.168.4
- typescript 4.8.3
- **Deno VSCode version**: v3.14.0

**Comment by ije** [comment]
thanks for reporting, just fixed! can you please try again?

**Comment by spencercap** [comment]
woot! all working now 👏 thank you
