### ISSUE TITLE
Failed to import - @danielx/civet

### ISSUE THREAD

**Issue by edemaine** [ije/esm.sh#448]
## Failing module

- **GitHub**: https://github.com/DanielXMoore/Civet
- **npm**: https://www.npmjs.com/package/@danielx/civet

```js
import { parse } from 'https://esm.sh/@danielx/civet@0.4.1-8.3'
```

## Error message

The contents of https://esm.sh/@danielx/civet@0.4.1-8.3 are:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: unreachable");
export default null;
```

## Additional info

- **esm.sh version**: ?
- **Browser version**: Chrome 107.0.5304.88

Perhaps we're doing something wrong; this was working in https://esm.sh/@danielx/civet@0.4.1-8.2
Is there a way to debug what's happening?

We recently added `require('node:readline')`, but this should not be in the main line of the code. Could this be the issue?

**Comment by ije** [comment]
Thanks for reporting~
The "unreachable" error means the `cjs-lexer` node process is down, you can try later it will be restarted automatically.  i upgraded the swc to latest, hope can improve the stability of the cjs lexer.
