### ISSUE TITLE
Repeat setting response header

### ISSUE THREAD

**Issue by kumv-net** [ije/esm.sh#453]
Repeat setting response header

Access-Control-Allow-Origin

![image](https://user-images.githubusercontent.com/70076074/203483939-36ecbbdd-fb8b-4e39-a8f7-bbcaadc6c748.png)

url：https://uno.antfu.me/play/

Access to fetch at 'https://esm.sh/@iconify-json/carbon@1.1.11/icons.json' (redirected from 'https://esm.sh/@iconify-json/carbon/icons.json') from origin 'https://uno.antfu.me' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ije** [comment]
thanks, just fixed
