### ISSUE TITLE
Failed to import maplibre-gl@1.15.3

### ISSUE THREAD

**Issue by rxliuli** [ije/esm.sh#454]
## Failing module

- **GitHub**: https://github.com/maplibre/maplibre-gl-js
- **npm**: https://www.npmjs.com/package/maplibre-gl/v/1.15.3

```js
import { Map } from 'https://esm.sh/maplibre-gl@1.15.3'
console.log('Map: ', Map)
```

## Error message

After `onload` I got this:

```
Uncaught SyntaxError: The requested module 'https://esm.sh/maplibre-gl@1.15.3?bundle' does not provide an export named 'Map'
```

## Additional info

- **esm.sh version**: latest
- **Browser version**: chrome latest

**Comment by ije** [comment]
this package is exported as umd(cjs in node) but declares the `type` as `module` in package.json, so the server can get the exports correctly.

try to use the default export, it may work:

```js
import gl from 'https://esm.sh/maplibre-gl@1.15.3'
console.log('Map: ', gl.Map)
```

<img width="400" alt="Screen Shot 2022-11-24 at 12 03 24" src="https://user-images.githubusercontent.com/2883484/203691404-a3009c5f-90a8-4742-9cab-c27426b07a17.png">

**Comment by rxliuli** [comment]
> this package is exported as umd(cjs in node) but declares the `type` as `module` in package.json, so the server can get the exports correctly.
> 
> try to use the default export, it may work:
> 
> ```js
> import gl from 'https://esm.sh/maplibre-gl@1.15.3'
> console.log('Map: ', gl.Map)
> ```
> 
> <img alt="Screen Shot 2022-11-24 at 12 03 24" width="400" src="https://user-images.githubusercontent.com/2883484/203691404-a3009c5f-90a8-4742-9cab-c27426b07a17.png">

Use named imports instead of default imports

```ts
- import gl from 'https://esm.sh/maplibre-gl@1.15.3'
+ import { Map } from 'https://esm.sh/maplibre-gl@1.15.3'
- console.log('Map: ', gl.Map)
+ console.log('Map: ', Map)
```

example: https://codepen.io/rxliuli/pen/WNyzLNo?editors=1111

**Comment by rxliuli** [comment]
Mainly I re-exported maplibre-gl in lib, like

```ts
export { Map as IMap } from 'maplibre-gl'
```

If this re-export method is wrong, how should I do it?

**Comment by ije** [comment]
you can create a PR to add this lib to https://github.com/ije/esm.sh/blob/afcc504a7e988421d528fb839197fcc8514183a9/server/node_services.go#L148
that can fix the exports.

**Comment by rxliuli** [comment]
> you can create a PR to add this lib to
> 
> https://github.com/ije/esm.sh/blob/afcc504a7e988421d528fb839197fcc8514183a9/server/node_services.go#L148
> 
> 
> that can fix the exports.

ok, let me try

**Comment by rxliuli** [comment]
> > you can create a PR to add this lib to
> > https://github.com/ije/esm.sh/blob/afcc504a7e988421d528fb839197fcc8514183a9/server/node_services.go#L148
> > 
> > that can fix the exports.
> 
> ok, let me try

I tried doing this and it works now in deno e.g. unit tests test/issue-454/issue-454.test.ts

https://github.com/ije/esm.sh/pull/455/files#diff-b36f6c84519f2657002cbb1d8731ea7a251ed92a8369b434bfda8bd715d7535b

But still error in browse, unless I add ?bundle parameter

```html
<script type="module">
  import { Map } from 'http://localhost:8080/maplibre-gl@1.15.3' // error
  import { Map } from 'http://localhost:8080/maplibre-gl@1.15.3?bundle' // success
  console.log('Map: ', Map)
</script>
```

**Comment by ije** [comment]
<img width="429" alt="Screen Shot 2022-11-24 at 17 44 05" src="https://user-images.githubusercontent.com/2883484/203750938-1d3400ca-b244-4aff-8979-73fd93678c64.png">
it works for me, no `?bundle` needed

**Comment by ije** [comment]
<img width="478" alt="Screen Shot 2022-11-24 at 19 28 19" src="https://user-images.githubusercontent.com/2883484/203773292-d5aa9ada-8bcf-400a-9b5f-0836854c0e15.png">

**Comment by rxliuli** [comment]
Confirm bug fix
![image](https://user-images.githubusercontent.com/24560368/203773820-6a288587-2692-4988-a9a4-f50f6a6a6f40.png)
