### ISSUE TITLE
Proposal: support query parameter options in path

### ISSUE THREAD

**Issue by chrisirhc** [ije/esm.sh#457]
This is simplify import map usage where the path is required to end with a trailing slash:

E.g.
```
{
  "some-library/": "https://esm.sh/some-library;ignore-annotations/"
}
```

The semicolon syntax is inspired by MDN article: https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname

Wanted to get thoughts on this first before doing a PR if there's interest.

I found this most useful when I need to set `?external=react,react-dom` on a library that exports multiple components on different paths to keep bundles small. 

E.g. https://baseweb.design

**Comment by chrisirhc** [comment]
Oh, looks like this is already supported as I was looking at the code, I guess I can make a PR of documenting it:
e.g. `https://esm.sh/baseui@12.2.0&external=react,react-dom/`

**Comment by ije** [comment]
yeah you found it, yes i didn't mention it in the readme, PR always is welcome!
