### ISSUE TITLE
CSS no longer returns compressed

### ISSUE THREAD

**Issue by traceypooh** [ije/esm.sh#460]
I'm using a v99 self-hosted setup
(our Dockerfile https://git.archive.org/www/esm/-/blob/main/Dockerfile )

Our prior v77 version was doing `brotli` compression for CSS and JS files.
v99 still does this for JS files (yay) but not CSS files anymore, eg:
https://esm.archive.org/@internetarchive/bookreader@5.0.0-47/BookReader/BookReader.css

Thanks for any help restoring this!

**Comment by ije** [comment]
thanks I will look into it

**Comment by traceypooh** [comment]
thanks!   And FWIW my devops mate says same for imagery, too (eg: svg, gif..)

**Comment by ije** [comment]
do you run the server behind a reverse proxy like Nginx？

**Comment by ije** [comment]
Please try to use https://github.com/ije/esm.sh/commit/254319ff35c6e90b4d43c4215b6a57c015b964e9, i just fixed compression of static content. Thanks!

**Comment by traceypooh** [comment]
Thanks so much for the crazy fast reply and work!  
Giving it a try now -- will report back and push to live if looks good...

**Comment by traceypooh** [comment]
Verified getting CSS & JS replies w/ brotli again, thanks!
Pushed it live to our self-hosted system.

I haven't seen compression for imagery (png, svg) in various testing so far.

**Comment by ije** [comment]
the server only compresses text file(js/css/svg/eg.) and the file size must larger than 1024 bytes
the gzip/br can not reduce size too much of compressed file like image and mainly it costs lot of cpu both in server and client

**Comment by traceypooh** [comment]
a perfect, that makes sense.  verified a > 1k .svg is brotli compresses when asked via headers now, too, for our live self-hosted system.

thanks so much!

**Comment by traceypooh** [comment]
ok, that makes sense, thanks.  i added a CI/CD test to check brotli for a larger svg we had.  thanks for the speedy work and replies!
