### ISSUE TITLE
Failed to import - preact@10.11.3/deno/compat.js

### ISSUE THREAD

**Issue by guifromrio** [ije/esm.sh#473]
## Failing module

In my import_map I have:

```
    "preact": "https://esm.sh/v96/preact@10.11.3",
    "preact/": "https://esm.sh/v96/preact@10.11.3/",
```

Something somehow maps to https://esm.sh/stable/preact@10.11.3/deno/compat.js 

Which gives a blank page for me, but 

https://esm.sh/v100/preact@10.11.3/deno/compat.js 

works just fine.

## Error message

After deploying to deno deploy, I get this:

![CleanShot 2022-12-25 at 22 51 31](https://user-images.githubusercontent.com/1633518/209490998-46356cef-68bc-409a-b425-3e35cc57c569.png)

## Additional info

- **esm.sh version**: v96, v99, v100, all exhibit the same behaviour.
- **Deno version**: 1.29.1

**Comment by ije** [comment]
seems it's cache problem, i just purge the cache now it works
