### ISSUE TITLE
Failed to import - @rjsf/validator-ajv8

### ISSUE THREAD

**Issue by lucis** [ije/esm.sh#475]
## Failing module

Deno Deploy is giving me a 500 because it can't import https://esm.sh/v96/@rjsf/validator-ajv8?target=deno

![image](https://user-images.githubusercontent.com/18706156/209570890-76605134-2069-4856-a0f9-a89e5134776e.png)

Error 1101 Ray ID: 77fb73a1da422603 • 2022-12-26 17:14:14 UTC
Worker threw exception

**Comment by ije** [comment]
fixed

**Comment by Songkeys** [comment]
May I ask how did you fix this issue? It seems it happens again now.
