### ISSUE TITLE
Depended module incorrect redirect when use `deps` option

### ISSUE THREAD

**Issue by Justinidlerz** [ije/esm.sh#476]
## Failing module
react-dom / graphQL

```js
import Loading from 'https://esm.sh/aftership-sdui-library@1.2.27/es2022/AntdExtends/Loading?bundle&deps=react@18,react-dom@18';

import errorLink from 'https://esm.sh/@apollo/client@3.5.10/link/error?bundle&deps=react@18,react-dom@18'
```

The module will load this module:

`https://esm.sh/react-dom@18.2.0/X-ZC9yZWFjdEAxOC4yLjA/es2022/react-dom.js`

Since the service upgrade to V100, failed to load some dependencies when setting the `deps` option for the module.

The correct URL must includes `/v100`: `https://esm.sh/v100/react-dom@18.2.0/X-ZC9yZWFjdEAxOC4yLjA/es2022/react-dom.js`

## Error message

After `onload` I got this:

```
throw new Error("[esm.sh] " + "parseCJSModuleExports: Package path ./X-ZC9yZWFjdEAxOC4yLjA/es2022/react-dom is not exported from package /tmp/esm-build-cc60c8eed435100cff08af96cf604ff44c4d6cee-9189bf32/node_modules/react-dom (see exports field in /tmp/esm-build-cc60c8eed435100cff08af96cf604ff44c4d6cee-9189bf32/node_modules/react-dom/package.json)");
export default null;
```

## Additional info

- **esm.sh version**: v100
- **Browser version**: *

**Comment by PeterBLITZ** [comment]
The error is present in other packages, even without any options.

e.g., `https://esm.sh/crypto-browserify@3.12.0/es2022/crypto-browserify.js`

**Comment by ije** [comment]
> https://esm.sh/crypto-browserify@3.12.0/es2022/crypto-browserify.js

this url is not correct (missing /`v100` prefix), where you got it?

**Comment by ije** [comment]
> import Loading from 'https://esm.sh/aftership-sdui-library@1.2.27/es2022/AntdExtends/Loading?bundle&deps=react@18,react-dom@18';

this you need to remove `es2022` part

**Comment by Justinidlerz** [comment]
But `es2022` is the server adds, I just only do this on my code:  
`https://esm.sh/aftership-sdui-library/AntdExtends/Loading?bundle&deps=react@18,react-dom@18'` 
![image](https://user-images.githubusercontent.com/7475347/209650845-9577c2f6-1aae-4e04-b44e-72a8aa27b636.png)

**Comment by ije** [comment]
<img width="1205" alt="Screenshot 2022-12-27 at 18 45 21" src="https://user-images.githubusercontent.com/2883484/209655233-4c708a48-e563-4891-b1c5-bea36369f69d.png">

i see, will look into it. thanks!

**Comment by Justinidlerz** [comment]
Wow, what is this tool? could you share it with me?

![image](https://user-images.githubusercontent.com/7475347/209656385-99819a2a-fdb8-43c4-8e81-945da8aec731.png)

**Comment by ije** [comment]
> Wow, what is this tool? looks so cool, could you share it with me?
> 
> ![image](https://user-images.githubusercontent.com/7475347/209656385-99819a2a-fdb8-43c4-8e81-945da8aec731.png)

by `deno info` command

**Comment by ije** [comment]
i found the bug, will deploy to prod after testing

**Comment by Justinidlerz** [comment]
Hello @ije, The `react-dom` is back to normal, but `graphql` still failed

![image](https://user-images.githubusercontent.com/7475347/209658655-8d7174ad-cb9d-4cec-b1a1-ae7ad3068ba7.png)

**Comment by ije** [comment]
it's cached, i need to release v101 to fix this, please wait

**Comment by Justinidlerz** [comment]
Okay, thanks

**Comment by PeterBLITZ** [comment]
> > https://esm.sh/crypto-browserify@3.12.0/es2022/crypto-browserify.js
> 
> this url is not correct (missing /`v100` prefix), where you got it?

I have a URL like this: `https://esm.sh/v100/crypto-browserify@3.12.0/es2022/crypto-browserify.bundle.js`, but inside, you can find incorrect relative import `import br from"/events@3.3.0/es2022/events.bundle.js";` without `/v100` prefix.


Unlike v99 `HTTPS://esm.sh/v99/crypto-browserify@3.12.0/es2022/crypto-browserify.bundle.js`, where we can find relative imports with prefix `import __events$ from "/v99/events@3.3.0/es2022/events.bundle.js";`

**Comment by ije** [comment]
@PeterBLITZ i believe v101 fixed this issue

**Comment by PeterBLITZ** [comment]
> @PeterBLITZ i believe v101 fixed this issue

Yup. Thank you)
