### ISSUE TITLE
Unnecessary bottom scroll bar on new website

### ISSUE THREAD

**Issue by ThaUnknown** [ije/esm.sh#478]
![image](https://user-images.githubusercontent.com/6506529/209700000-8b278cbd-8407-4661-b9f5-8cd9adb7c6c7.png)

I couldn't find the repository for the new website, I assume it's private
```patch
#hero {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
-   width: 100vw;
    min-height: 100vh;
}
```
will fix the issue
also
```patch
#summary .wrapper {
+   gap: 30px;
    max-width: 1000px;
    padding-bottom: 160px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}
```
will make the summary section look better on some 4:3 displays

**Comment by ije** [comment]
just updated! thanks!
