### ISSUE TITLE
Failed to import - @mdx-js/runtime

### ISSUE THREAD

**Issue by sandro-qiang** [ije/esm.sh#479]
>Access to script at 'https://esm.sh/v102/node_buffer.js' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No '>Access-Control-Allow-Origin' header is present on the requested resource.

no `access-control-allow-origin: *` in `https://esm.sh/v102/node_buffer.js`'s header, other modules ok.

use `import MDX from 'https://esm.sh/@mdx-js/runtime'` directly in script tag of html

**Comment by ije** [comment]
<img width="426" alt="Screenshot 2022-12-29 at 22 27 50" src="https://user-images.githubusercontent.com/2883484/209967246-dacea337-f99a-494d-9f92-2140f4968a3a.png">

seems it works for me

**Comment by sandro-qiang** [comment]
![image](https://user-images.githubusercontent.com/44429952/209970245-a437feec-eb09-49da-9954-3df4bcb5b5ad.png)

maybe browser or network issue ?

**Comment by ije** [comment]
what browser are you using?

**Comment by sandro-qiang** [comment]
![image](https://user-images.githubusercontent.com/44429952/209979107-93590a51-7e16-45e3-b657-c78e050aa427.png)

Edge on Ubuntu 20.04

**Comment by ije** [comment]
i just updated the CDN to make sure the `Origin` header will be a part of the cache key, may can help. can you please try again? thanks!

**Comment by sandro-qiang** [comment]
It works, thanks!
