### ISSUE TITLE
Failed to import - @use-gesture/react

### ISSUE THREAD

**Issue by paulshen** [ije/esm.sh#483]
## Failing module

- **GitHub**: https://github.com/pmndrs/use-gesture/tree/main/packages/react
- **npm**: https://www.npmjs.com/package/@use-gesture/react

```js
import { useDrag } from 'https://esm.sh/@use-gesture/react'
```

## Error message

After `onload` I got this: I get a 500 response from a dependent package `@use-gesture/core/types`

https://esm.sh/v102/@use-gesture/core@10.2.23/es2022/types.js

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Package path ./types/dist/use-gesture-core-types.esm is not exported from package /tmp/esm-build-39bc78b9fffc290bc5014872971fa00181218847-176c8add/node_modules/@use-gesture/core (see exports field in /tmp/esm-build-39bc78b9fffc290bc5014872971fa00181218847-176c8add/node_modules/@use-gesture/core/package.json)");
export default null;
```

Looks like the types package only exports TypeScript types

## Additional info

- **esm.sh version**: v102
- **Browser version**: Arc / Chromium Engine Version 108.0.5359.125

**Comment by ije** [comment]
thanks, i will look into it

**Comment by paulshen** [comment]
I tried looking into this but am having trouble figuring it out. My hunch is that it's because this is an empty file https://unpkg.com/browse/@use-gesture/core@10.2.23/types/dist/use-gesture-core-types.esm.js

**Comment by ije** [comment]
will release **v105** soon that should fix this

**Comment by paulshen** [comment]
Thank you @ije!
