### ISSUE TITLE
Playground fails to load because of CORS error loading `monaco-editor`

### ISSUE THREAD

**Issue by cowboyd** [ije/esm.sh#490]
Trying to access https://playground.esm.sh, the screen just hangs forever in a `loading` state. It appears to be a problem loading the `monaco-editor` module.

**chrome** 108.0.5359.124 (Official Build) (arm64)
**safari** 16.1 (18614.2.9.1.12)
```
Access to script at 'https://esm.sh/v102/monaco-editor@0.34.1/es2022/monaco-editor.js' from origin 'https://playground.esm.sh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
monaco-editor.js:1          Failed to load resource: net::ERR_FAILED
```

![image showing hanging load screen with CORS error](https://user-images.githubusercontent.com/4205/211350459-00d28782-6fce-401a-b11b-783e6a9563b4.png)

**Comment by cowboyd** [comment]
This may be related, but I encountered this while trying to integrate `Monaco` into the Fresh web framework. https://github.com/cowboyd/monaco-fresh#dynamic-import

**Comment by ije** [comment]
@cowboyd  sorry i can't repeat this, can you please check if your browser is sending the `Origin` header?

**Comment by cowboyd** [comment]
Turns out it was a caching issue. I was seeing it in both Chrome and Safari and _only_ for the `monaco-editor` module, but all the other modules were fine. My browser must have been saving a wonky response somewhere, because when I completely wiped by cache on both browsers, the problem went away 🤷🏻‍♂️
