### ISSUE TITLE
Failed to import - shit is down

### ISSUE THREAD

**Issue by imjamesb** [ije/esm.sh#491]
Shit is down everywhere.

![image](https://user-images.githubusercontent.com/35933830/211447058-67b37c0a-32df-49a3-ae49-d521c9c31507.png)

**Comment by Justinidlerz** [comment]
See the problem is the same as mine, I think this is caused by CDN config. Also can see #492
@ije Could you please help to check this one

**Comment by mashaal** [comment]
Seems to only effect imports w/o a version number

https://esm.sh/react
https://esm.sh/react@18.2.0

https://esm.sh/npm
https://esm.sh/npm@9.2.0

**Comment by ije** [comment]
now it should work

**Comment by ije** [comment]
<img width="753" alt="Screenshot 2023-01-10 at 14 07 12" src="https://user-images.githubusercontent.com/2883484/211474231-ef7a84b7-8430-4a74-a1f4-29594af53ede.png">

I also updated the checklist, hope this not happen again (unless i can get the checking error by email in time and shows here https://esm.instatus.com/)

**Comment by ije** [comment]
FYI, the broken is caused by my bad update, i was adding support of `https://esm.sh/react-dom@18&dev/client` to support import maps "/" suffix with query parameters.

**Comment by lino-levan** [comment]
@ije Just wanted to let you know if you weren't already aware. It looks like `preact-render-to-string` was broken in a recent update. Not sure if it is related to this or not, but certainly feels like it considering the timing. 

A lot of discussion on discord: https://discord.com/channels/684898665143206084/1062204030836809778/1062204030836809778

**Comment by ije** [comment]
@lino-levan thanks, just fixed
