### ISSUE TITLE
Failed to import - Any packages without pinned version

### ISSUE THREAD

**Issue by Justinidlerz** [ije/esm.sh#492]
## Failing module

Any packages without pined version

![image](https://user-images.githubusercontent.com/7475347/211447176-bd87705c-e7d8-438e-88ff-7cff89db9761.png)

But succeed on packages within any version suffix`react@18123213213`

![image](https://user-images.githubusercontent.com/7475347/211447786-d73fbaa7-1778-4935-aebc-cc08bb79ff5b.png)

## Error message
![image](https://user-images.githubusercontent.com/7475347/211447268-6ed7c358-1cf6-4311-9223-d4c73adbfadd.png)

## Additional info

- **esm.sh version**: 102
- **Browser version**:  chrome *

**Comment by aliuq** [comment]
I got the same error

**Comment by ije** [comment]
fixed, pls check messsage in https://github.com/ije/esm.sh/issues/491, thanks
