### ISSUE TITLE
Failed to import - https://esm.sh/*preact-render-to-string@5.2.3

### ISSUE THREAD

**Issue by lucacasonato** [ije/esm.sh#493]
The `*` prefix syntax before NPM specifier names does not work anymore:

`https://esm.sh/*preact-render-to-string@5.2.3` imports `"https://esm.sh/stable/preact@10.11.3/deno/preact.js"` instead of importing `"preact"`. This causes import map remapping to break.

**Comment by ije** [comment]
i am looking into it.

**Comment by ije** [comment]
<img width="1004" alt="Screenshot 2023-01-10 at 18 40 16" src="https://user-images.githubusercontent.com/2883484/211529829-0af8c5cc-f545-420f-a072-b94ef11b5557.png">
just fixed it and purged the cache, now it should work fine

**Comment by lucacasonato** [comment]
Thank you so much @ije! :heart:
