### ISSUE TITLE
https://esm.sh/react@18.2.0?dev/jsx-runtime serves "react.js"

### ISSUE THREAD

**Issue by cristiano-belloni** [ije/esm.sh#494]
If I try to get `https://esm.sh/react@18.2.0?dev/jsx-runtime` (or whatever React version), esm.sh responds with:

```
/* esm.sh - react@18.2.0 */
export * from "https://esm.sh/stable/react@18.2.0/es2022/react.js";
export { default } from "https://esm.sh/stable/react@18.2.0/es2022/react.js";
```

 Before the last changes (possibly related to https://github.com/ije/esm.sh/issues/491), it used to respond:
 
 ```
 /* esm.sh - react@18.2.0/jsx-runtime */
export * from "https://esm.sh/stable/react@18.2.0/es2022/jsx-runtime.development.js";
export { default } from "https://esm.sh/stable/react@18.2.0/es2022/jsx-runtime.development.js";
```

This is breaking many deployed applications at run-time.

**Comment by dsherret** [comment]
I think it's supposed to have the query parameter on the end of the url after the path https://esm.sh/react@18.2.0/jsx-runtime?dev

**Comment by cristiano-belloni** [comment]
> I think it's supposed to have the query parameter on the end of the url after the path https://esm.sh/react@18.2.0/jsx-runtime?dev

It's always worked the other way, plus it seems that https://esm.sh/react@18.2.0&dev/jsx-runtime works as intended (@ije any idea why? I saw it mentioned in https://github.com/ije/esm.sh/issues/491#issuecomment-1376785130)

**Comment by ije** [comment]
@cristiano-belloni i agree with you, i added support of https://esm.sh/react@18.2.0&dev/jsx-runtime to support import maps "/" suffix with query, but we should support https://esm.sh/react@18.2.0?dev/jsx-runtime as well for jsx transformer.
i will fix it very soon, thanks!

**Comment by ije** [comment]
just updated, now it works just like before
