### ISSUE TITLE
Failed to import and requireModeAllowList

### ISSUE THREAD

**Issue by shishkin** [ije/esm.sh#501]
I would just like to understand better and maybe discuss any improvements on a common issue that looks like:

```
The requested module '....' does not provide an export named '...'
```

Searching for similar issues here I see the solution happens to be to add the package into `requireModeAllowList`. Could someone please explain the root cause of the error and how adding `requireMode` argument solves it. Sorry, I'm new to esm.sh.

Also, maybe it would be useful to add query string parameter to force `requireMode` without hardcoding failing packages?

**Comment by ije** [comment]
The `requireMode` imports npm packages in the node process, that is not safe if we allow any packages to do that. you can make a pr to update the `requireModeAllowList`, but only safe/popular packages will be approved.
