### ISSUE TITLE
Failed to import plotly.js@2.17.1

### ISSUE THREAD

**Issue by ayame113** [ije/esm.sh#502]
## Failing module

- **GitHub**: https://github.com/plotly/plotly.js
- **npm**: https://www.npmjs.com/package/plotly.js

```js
import Plotly from "https://esm.sh/plotly.js@2.17.1";
```

## Error message

After `onload` I got this:

```
Uncaught SyntaxError: Unexpected identifier '#_contains$' (at d.js:2:25)
```

## Additional info

https://esm.sh/v103/d@1.0.1/esnext/d.js seems to have a syntax error.

![image](https://user-images.githubusercontent.com/40050810/213455398-34debce2-79d5-4d8b-a880-9feec2881fe8.png)

- **esm.sh version**: v103
- **Browser version**: Google Chrome 108.0.5359.126

P.S.: Thank you for creating this amazing project!

**Comment by ije** [comment]
just fixed the weird "/#/" path of es5-ext, will

**Comment by ije** [comment]
v104 may fix this, can you please try again?

**Comment by ayame113** [comment]
This error seems to have been fixed, thank you!
However I'm still getting another error, so I'll open a new issue about it.
