### ISSUE TITLE
Failed to import types - React, connection timed out

### ISSUE THREAD

**Issue by KyleJune** [ije/esm.sh#508]
## Failing module

- **GitHub**: https://github.com/facebook/react
- **npm**: https://www.npmjs.com/package/react

```js
import "https://esm.sh/react@18.2.0/jsx-runtime?target=deno&pin=v104";
```

## Error message

I noticed each time my script runs, it would keep trying to download the types. This made me think the request was failing, causing it to not get cached and causing it to retry downloading it each time the script ran.

```
Download https://esm.sh/v103/@types/react@^18/jsx-dev-runtime~.d.ts
```

If I go to the [module url](https://esm.sh/react@18.2.0/jsx-runtime?target=deno&pin=v104) and check dev tools network tab, I can see it responds with a matching x-typescript-types header.

```
x-typescript-types | https://esm.sh/v104/@types/react@^18/jsx-runtime~.d.ts
```

Here is the error I get if I go to that [types url](https://esm.sh/v104/@types/react@^18/jsx-runtime~.d.ts).

![image](https://user-images.githubusercontent.com/3241653/215028694-de6369c8-a343-4851-afb6-ba579983b99d.png)

## Additional info

- **esm.sh version**: v104
- **Deno version**: 1.29.4

**Comment by ije** [comment]
now it works, this is cursed by loop redirects between the CDN and the esm server

**Comment by ije** [comment]
thanks for reporting

**Comment by KyleJune** [comment]
Thanks for the quick fix.
