### ISSUE TITLE
Failed to import - react-svg-spinners

### ISSUE THREAD

**Issue by marcushultman** [ije/esm.sh#512]
## Failing module

- **GitHub**: https://github.com/dephraiim/react-svg-spinners
- **npm**: https://www.npmjs.com/package/react-svg-spinners

```js
import { NinetyRing } from 'https://esm.sh/react-svg-spinners@0.3.1';
```

## Error message

After running `deno run` I got this:

```
error: Uncaught (in promise) SyntaxError: The requested module 'https://esm.sh/react-svg-spinners@0.3.1' does not provide an export named 'NinetyRing'
  await import(entrypoint);
```

## Additional info

- **esm.sh version**: v106
- **Deno version**: 1.30.0

**Comment by marcushultman** [comment]
default import seems to work. It contains all components on a POJO.

**Comment by ije** [comment]
the server can not resolve the cjs exports correctly, so i just added `?cjs-export` option as workaround for it

**Comment by ije** [comment]
try 
```js
import { NinetyRing, NinetyRingWithBg } from "https://esm.sh/react-svg-spinners@0.3.1?cjs-exports=NinetyRing,NinetyRingWithBg"
```

**Comment by marcushultman** [comment]
@ije Amazing! Thank you for the quick turn-around.
