### ISSUE TITLE
Redirect URLs not using https on localhost proxy

### ISSUE THREAD

**Issue by jaredcwhite** [ije/esm.sh#526]
I'm trying out esm.sh on my home server (pretty awesome!), and I'm using Caddy to reverse proxy localhost. I ran into an issue where redirects to qualified full versions were using `http://` as the prefix instead of `https://`. I was able to track it down to this line:
https://github.com/ije/esm.sh/blob/d285cad2657af6c3f0c7e89bbc9df6ec8f044292/server/handler.go#L144

I ended up patching that line like so:

```go
if ctx.R.TLS != nil || strings.HasPrefix(cfg.Origin, "https://") {
```

So then it uses the correct protocol due to the Origin starting with `https`.

I'm not sure if that's the ideal solution in the long run, so I wanted to run it by you before trying to submit a PR. (Also a word of warning: I'm not very experienced with Go… 😅)

**Comment by ije** [comment]
if you already configured the `origin` option it would ignore the `ctx.R.TLS`

**Comment by jaredcwhite** [comment]
@ije Well, the problem isn't with `cdnOrigin`, it's with `reqOrigin`. Because of this line

https://github.com/ije/esm.sh/blob/d285cad2657af6c3f0c7e89bbc9df6ec8f044292/server/handler.go#L147

`reqOrigin` gets set with `http` in the scenario I described above, and that value seems to be used in a number of places to construct redirect URLs. That was another thought I had…maybe the redirects should be using `cdnOrigin` rather than `reqOrigin`, but I was nervous to recommend changing those because maybe that breaks something I'm not aware of around how the CDN infra works.

**Comment by ije** [comment]
did you add the `origin` option in the `config.json` ?

**Comment by jaredcwhite** [comment]
Yes, definitely. It's the public hostname with https, reverse proxied via Caddy

**Comment by ije** [comment]
i see. you are correct, should use `cdnOrigin` instead of `reqOrigin` when redirecting

**Comment by ije** [comment]
would you like to make a PR?

**Comment by jaredcwhite** [comment]
@ije Sure I can work on it. I might need some help with tests if I don't figure that out. As I mentioned, I'm not experienced with Go (JS and Ruby dev primarily).

**Comment by ije** [comment]
you done it great 👍
