### ISSUE TITLE
version resolution errors

### ISSUE THREAD

**Issue by randyhoulahan** [ije/esm.sh#528]
https://esm.sh/vue => https://esm.sh/vue@3.2.47 = good

https://esm.sh/vue@^3.2.47 => https://esm.sh/vue@3.3.0-alpha.4 = bad

to esm:

https://esm.sh/v107/vue-demi@0.13.11/es2022/vue-demi.js

vue is defaulted to https://esm.sh/vue@3.3.0-alpha.4 in code above  which it should be  https://esm.sh/vue@3.2.47

**Comment by ije** [comment]
seems this is caused by change #525, i will look into it

**Comment by ije** [comment]
`[https://esm.sh/vue@^3.2.47](https://esm.sh/vue@%5E3.2.47)` now works correctly, for `vue-demi` you can specify the vue version by adding `?deps=vue@3.2.47`
