### ISSUE TITLE
Failed to import - UUID / Buffer

### ISSUE THREAD

**Issue by sgb-io** [ije/esm.sh#533]
## Failing module

- **GitHub**: https://github.com/uuidjs/uuid
- **npm**: https://www.npmjs.com/package/uuid

```js
import uuid from 'https://esm.sh/v109/uuid@8.3.2/es2022/uuid.js'
```

It contains this statement:

```js
import { Buffer as __Buffer$ } from "/v109/node_buffer.js"
```

Which leads to `https://esm.sh/v109/node_buffer.js`

This url (`https://esm.sh/v109/node_buffer.js`) is currently returning a Cloudflare 1016 Origin DNS error.

**Comment by sgb-io** [comment]
This also seems to affect the playground: https://playground.esm.sh/

**Comment by ije** [comment]
fixed, sorry for an invalid config update of the CDN

**Comment by sgb-io** [comment]
@ije Thanks for the speedy response!

**Comment by ije** [comment]
> This also seems to affect the playground: https://playground.esm.sh/

i updated the playground url to https://code.esm.sh/

**Comment by ije** [comment]
fyi, i just updated the checker script to avoid this happens again
<img width="474" alt="Screenshot 2023-03-01 at 17 53 50" src="https://user-images.githubusercontent.com/2883484/222105253-1e2b679a-4fd9-4357-bf80-ca36e6248dcd.png">
