### ISSUE TITLE
Failed to import - v103/linkedom@0.14.21

### ISSUE THREAD

**Issue by iugo** [ije/esm.sh#534]
## Failing module

- **GitHub**: https://github.com/WebReflection/linkedom
- **npm**:

```js
import { DOMParser } from 'https://esm.sh/v103/linkedom@0.14.21';
```

## Error message

After running `deno check` I got this:

```
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'DOMParser'.
import { DOMParser } from 'https://esm.sh/v103/linkedom@0.14.21';
```

## Additional info

- **esm.sh version**: v103, v108, v109
- **Deno version**: 1.31.1

success in esm.sh v102.

**Comment by ije** [comment]
<img width="938" alt="Screenshot 2023-03-01 at 17 43 35" src="https://user-images.githubusercontent.com/2883484/222102169-4223bb4b-9335-4249-9ec3-c7ddad32833e.png">
seems it works for me

**Comment by iugo** [comment]
> seems it works for me

@ije  works with `deno run`, but error with `deno check` and `deno compile`.

**Comment by ije** [comment]
seems it's types issues, i will look into it thanks 👍

**Comment by kt3k** [comment]
Looks like the Content-Type of .d.ts files became `application/json` in the recent update?

**Comment by ker0olos** [comment]
> success in esm.sh v102.
I tested it, and It does not work with any version. It most likely worked with v102 for the issue author because that's the version they had cached before the issue occurred.

**Comment by ije** [comment]
<img width="531" alt="Screenshot 2023-03-02 at 07 45 31" src="https://user-images.githubusercontent.com/2883484/222292632-5499184c-774a-437c-a386-c484e0d09177.png">
fixed in v110, and updated the checker script

**Comment by ije** [comment]
> > success in esm.sh v102.
> 
> I tested it, and it doesn't work with any version. It most likely worked with `v102` for the issue author because that's the version they had cached before the issue occurred.

@ker0olos v109 i switch to use CF R2 to store store those the dts files, but a mistake using same `application/json` witch i added before for source map output

**Comment by ije** [comment]
> <img alt="Screenshot 2023-03-02 at 07 45 31" width="531" src="https://user-images.githubusercontent.com/2883484/222292632-5499184c-774a-437c-a386-c484e0d09177.png">
> 
> fixed in v110, and updated the checker script

i am going to close this issue, the checker script should avoid this happens again
