### ISSUE TITLE
Failed to import -

### ISSUE THREAD

**Issue by tlgimenes** [ije/esm.sh#535]
## Failing module

Preact / Deno Fresh

```sh
deno info https://esm.sh/preact@10.11.3
```

## Error message
After [this commit](https://github.com/ije/esm.sh/commit/b5236c44a28df74aaf257a757511bec654848ee5), running 
```sh
deno info --json https://esm.sh/preact@10.11.3
```

we get the following response:

```sh
"specifier": "https://esm.sh/v102/preact@10.11.3/src/index.d.ts",
 "error": "Expected a JavaScript or TypeScript module, but identified a Json module. Consider importing Json modules with an import assertion with the type of \"json\".\n  Specifier: https://esm.sh/v102/preact@10.11.3/src/index.d.ts"
```

This breaks typings on Deno Fresh. 

## Additional info

- **esm.sh version**: latest
- **Deno version**: 1.31.1

**Comment by ije** [comment]
<img width="531" alt="Screenshot 2023-03-02 at 07 45 31" src="https://user-images.githubusercontent.com/2883484/222292632-5499184c-774a-437c-a386-c484e0d09177.png">
fixed in v110, and updated the checker script

**Comment by ije** [comment]
duplicate to #534
