### ISSUE TITLE
Failed to import - date-fns@2.29.3 http 500

### ISSUE THREAD

**Issue by pki-acs** [ije/esm.sh#538]
The error I get is:

```
Import 'https://esm.sh/date-fns@2.29.3' failed: 500 Internal Server Error
```

**Comment by ije** [comment]
<img width="1368" alt="Screenshot 2023-03-04 at 22 46 03" src="https://user-images.githubusercontent.com/2883484/222909875-24cac861-08c0-4907-a509-f94c9ff951ce.png">
i am looking into it

**Comment by ije** [comment]
it works now, seems the yarn cache broken
