### ISSUE TITLE
Typescript dts files

### ISSUE THREAD

**Issue by timreichen** [ije/esm.sh#58]
Seems like dts files are not correctly transformed. 
```ts
import tsvfs from "https://esm.sh/@typescript/vfs"
console.log(tsvfs);
```
```sh
error: TS2694 [ERROR]: Namespace '"https://cdn.esm.sh/v41/@types/lz-string@1.3.34/index.d.ts"' has no exported member 'LZStringStatic'.
    at https://cdn.esm.sh/v41/@typescript/vfs@1.3.4/dist/index.d.ts:58:176
```

**Comment by KyleJune** [comment]
I encountered a similar issue related to the lz-string module's exports. It appears to not just be an issue with the types. Importing compressToEncodedURIComponent from it doesn't work for me even if I add no-check.

https://github.com/alephjs/esm.sh/issues/248

**Comment by timreichen** [comment]
Closing this issue because it is out of date. Feel free to reopen if this is still an issue.
