### ISSUE TITLE
Support storage interface

### ISSUE THREAD

**Issue by fakership** [ije/esm.sh#76]
i have a question about code， the  `esm.x-static.io`  should be a cdn domain，but i can not find when you upload the resource in stoage|type to cdn。

**Comment by fakership** [comment]
help

**Comment by ije** [comment]
normally, you don't need to upload the files, CDN will cache files on demand

**Comment by fakership** [comment]
the question is that if you first visit https://esm.sh/react for example，you will store it in storage/builds dir，and esm.x-static.io will back-to-source the esm.sh server to get the resource,  is right?
but, you have to ensure that the react have to always exits in storage/builds dir disk, or you will rebuild, so how can ensure the resource always exist in docker?

**Comment by fakership** [comment]
i am really confused, thank you

**Comment by fakership** [comment]
> normally, you don't need to upload the files, CDN will cache files on demand
you mean back-to-resource ?

**Comment by fakership** [comment]
and how deal with multi instance

**Comment by ije** [comment]
i see, maybe we can implement a storage interface in the future to store builds to any location, like aws-s3/aliyun-oss for example, for now we store files in local fs.

**Comment by ije** [comment]
i just added a storage interface to the server that is compat with previous db/fs, next i will add mysql/postgres/aliyun-oss/aws-s3/... implements.
