### ISSUE TITLE
[Feature request] customize X-TypeScript-Types

### ISSUE THREAD

**Issue by codehz** [ije/esm.sh#79]
Usecase:
The upstream type definition is not good enough or even doesn't exists

Workaround:
* DENO
use `// @deno-types="xxx"` before import statment
problem:
you need write it many times if you have reference it in many files

Propose change:
add options: `?dts=<custom url>` and make server response with this custom url as X-TypeScript-Types

**Comment by ije** [comment]
try write it in `deps.ts`
